// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficIncidentsOpitech.Infrastructure.Persistence;

#nullable disable

namespace TrafficIncidentsOpitech.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrafficIncidentsDbContext))]
    partial class TrafficIncidentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafficIncidentsOpitech.Domain.Incidents.TrafficIncidentAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VictimCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Department", "OccurredAt");

                    b.ToTable("TrafficIncidents", (string)null);
                });

            modelBuilder.Entity("TrafficIncidentsOpitech.Domain.Incidents.TrafficIncidentAggregate", b =>
                {
                    b.OwnsMany("TrafficIncidentsOpitech.Domain.Incidents.InvolvedVehicle", "InvolvedVehicles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Notes")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Plate")
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<Guid>("TrafficIncidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("VehicleType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("TrafficIncidentId");

                            b1.ToTable("TrafficIncidentVehicles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TrafficIncidentId");
                        });

                    b.Navigation("InvolvedVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
